// Code generated by "stringer -type FeatureName -output webgpu2_string.go"; DO NOT EDIT.

package wgpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeatureNameUndefined-0]
	_ = x[FeatureNameDepthClipControl-1]
	_ = x[FeatureNameDepth32FloatStencil8-2]
	_ = x[FeatureNameTimestampQuery-3]
	_ = x[FeatureNameTextureCompressionBC-4]
	_ = x[FeatureNameTextureCompressionETC2-5]
	_ = x[FeatureNameTextureCompressionASTC-6]
	_ = x[FeatureNameIndirectFirstInstance-7]
	_ = x[FeatureNameShaderF16-8]
	_ = x[FeatureNameRG11B10UfloatRenderable-9]
	_ = x[FeatureNameBGRA8UnormStorage-10]
	_ = x[FeatureNameFloat32Filterable-11]
	_ = x[NativeFeatureNamePushConstants-196609]
	_ = x[NativeFeatureNameTextureAdapterSpecificFormatFeatures-196610]
	_ = x[NativeFeatureNameMultiDrawIndirect-196611]
	_ = x[NativeFeatureNameMultiDrawIndirectCount-196612]
	_ = x[NativeFeatureNameVertexWritableStorage-196613]
	_ = x[NativeFeatureNameTextureBindingArray-196614]
	_ = x[NativeFeatureNameSampledTextureAndStorageBufferArrayNonUniformIndexing-196615]
	_ = x[NativeFeatureNamePipelineStatisticsQuery-196616]
	_ = x[NativeFeatureNameStorageResourceBindingArray-196617]
	_ = x[NativeFeatureNamePartiallyBoundBindingArray-196618]
}

const (
	_FeatureName_name_0 = "FeatureNameUndefinedFeatureNameDepthClipControlFeatureNameDepth32FloatStencil8FeatureNameTimestampQueryFeatureNameTextureCompressionBCFeatureNameTextureCompressionETC2FeatureNameTextureCompressionASTCFeatureNameIndirectFirstInstanceFeatureNameShaderF16FeatureNameRG11B10UfloatRenderableFeatureNameBGRA8UnormStorageFeatureNameFloat32Filterable"
	_FeatureName_name_1 = "NativeFeatureNamePushConstantsNativeFeatureNameTextureAdapterSpecificFormatFeaturesNativeFeatureNameMultiDrawIndirectNativeFeatureNameMultiDrawIndirectCountNativeFeatureNameVertexWritableStorageNativeFeatureNameTextureBindingArrayNativeFeatureNameSampledTextureAndStorageBufferArrayNonUniformIndexingNativeFeatureNamePipelineStatisticsQueryNativeFeatureNameStorageResourceBindingArrayNativeFeatureNamePartiallyBoundBindingArray"
)

var (
	_FeatureName_index_0 = [...]uint16{0, 20, 47, 78, 103, 134, 167, 200, 232, 252, 286, 314, 342}
	_FeatureName_index_1 = [...]uint16{0, 30, 83, 117, 156, 194, 230, 300, 340, 384, 427}
)

func (i FeatureName) String() string {
	switch {
	case i <= 11:
		return _FeatureName_name_0[_FeatureName_index_0[i]:_FeatureName_index_0[i+1]]
	case 196609 <= i && i <= 196618:
		i -= 196609
		return _FeatureName_name_1[_FeatureName_index_1[i]:_FeatureName_index_1[i+1]]
	default:
		return "FeatureName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
